name: soda_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  agora_rtc_engine:
    # path: Agora-Flutter-SDK/
    git:
      url: https://github.com/Rajeshree777/Agora-Flutter-SDK.git
#      ref: exclude_banuba                      # remove (this line)ref if want banuba
  camera:
    git:
      url: https://github.com/Rajeshree777/plugins.git
      path: packages/camera/camera
      ref: orientation_issue

  cupertino_icons: ^1.0.0

  flutter_screenutil: 1.0.2

  flutter_svg: ^0.21.0-nullsafety.0

  google_fonts: ^2.0.0
  wakelock: ^0.4.0
  permission_handler: ^6.1.3
  firebase_analytics: ^8.1.0
  firebase_crashlytics: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/roboto_regular_fonts.ttf
          weight: 400
        - asset: assets/fonts/roboto_medium_fonts.ttf
          weight: 500
        - asset: assets/fonts/roboto_bold_fonts.ttf
          weight: 600
        - asset: assets/fonts/roboto_black_fonts.ttf
          weight: 700
    - family: DancingFonts
      fonts:
        - asset: assets/fonts/dancing_fonts.ttf
    - family: IndieFlowers
      fonts:
        - asset: assets/fonts/indie_flowers_fonts.ttf
    - family: OI
      fonts:
        - asset: assets/fonts/oi_fonts.ttf
    - family: RobotoItalic
      fonts:
        - asset: assets/fonts/roboto_italic.ttf
    - family: Akaya
      fonts:
        - asset: assets/fonts/akaya_fonts.ttf
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/josefin_fonts.ttf
    - family: GreatVibes
      fonts:
        - asset: assets/fonts/great_vibes_fonts.ttf
    - family: InformalRoman
      fonts:
        - asset: assets/fonts/informal_roman_fonts.ttf
    - family: Calibri
      fonts:
        - asset: assets/fonts/calibri_fonts.ttf
    - family: ImprintMT
      fonts:
        - asset: assets/fonts/imprint_mt_fonts.ttf
    - family: Infroman
      fonts:
        - asset: assets/fonts/infroman_fonts.ttf
    - family: RobotoRegular
      fonts:
       - asset: assets/fonts/roboto_regular_fonts.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/oswald_regular_fonts.ttf
    - family: Kalam
      fonts:
        - asset: assets/fonts/kalam_regular_fonts.ttf
    - family: Satisfy
      fonts:
        - asset: assets/fonts/satisfy_regular_fonts.ttf
    - family: Domine
      fonts:
        - asset: assets/fonts/domine_regular_fonts.ttf
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/roboto_bold_fonts.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/roboto_medium_fonts.ttf
    - family: AlegreyaCaps
      fonts:
        - asset: assets/fonts/alegreya_caps_fonts.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
