// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

package com.banuba.sdk.effect_player;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public final class AnalyticsConfig {
    /*package*/ final int framesCount;

    /*package*/ final int delayForRecordWithFace;

    /*package*/ final String outputPath;

    public AnalyticsConfig(
        int framesCount, int delayForRecordWithFace, @NonNull String outputPath) {
        this.framesCount = framesCount;
        this.delayForRecordWithFace = delayForRecordWithFace;
        this.outputPath = outputPath;
    }

    /** Number of frames to record when face was found */
    public int getFramesCount() {
        return framesCount;
    }

    /** Number of frames to skip before record start */
    public int getDelayForRecordWithFace() {
        return delayForRecordWithFace;
    }

    /** Path to folder for results storing */
    @NonNull
    public String getOutputPath() {
        return outputPath;
    }

    @Override
    public String toString() {
        return "AnalyticsConfig{"
            + "framesCount=" + framesCount + ","
            + "delayForRecordWithFace=" + delayForRecordWithFace + ","
            + "outputPath=" + outputPath + "}";
    }
}
