// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

package com.banuba.sdk.effect_player;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public interface AnalyticsListener { public void onAnalyticsEvent(@NonNull String filePath); }
